---
- hosts: docker-hosts
  remote_user: root
  roles:
    - common
    - rhsm
  tasks:
    - name: "If docker is installed, maybe we are running this playbook on a server where it already ran?"
      shell:
        "! rpm -q docker"
    - name: "Enable RHEL Extras repo where docker package lives"
      command:
        subscription-manager repos --enable 'rhel-{{ ansible_distribution_major_version }}-server-extras-rpms'
    - name: "docker package installed"
      yum:
        name=docker
        state=present
    - name: "docker service not running"
      service:
        name=docker
        state=stopped
        enabled=no
    - name: "Volume group on ephemeral drives exists"
      shell: |
        pvcreate --yes /dev/xvdb
        [ -e /dev/xvdc ] \
            && pvcreate --yes /dev/xvdc
        [ -e /dev/xvdc ] \
            && vgcreate docker /dev/xvdb /dev/xvdc \
            || vgcreate docker /dev/xvdb
    - name: "Docker storage related config ready to be recreated"
      shell: |
        rm -rf /var/lib/docker
        rm -f /etc/sysconfig/docker-storage
    - name: "docker-storage-setup configured to use our new volume group"
      lineinfile:
        dest=/etc/sysconfig/docker-storage-setup
        regexp="^VG="
        line="VG='docker'"
    - name: "docker-storage-setup"
      command:
        docker-storage-setup
    - name: "docker service restarted to use new settings"
      service:
        name=docker
        state=restarted
        enabled=no
    - name: "Dockerfile for base container present"
      copy:
        src=Dockerfile
        dest=/root/Dockerfile
    - name: "Base container built"
      shell:
        docker build -t r7perfsat - < /root/Dockerfile
    - name: "EPEL enabled"
      command:
        rpm -ivh "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    - name: "Package ansible installed"
      yum:
        name=ansible
        state=installed
    - name: "Ansible should not check host keys"
      command:
        sed -i 's|^.*host_key_checking.*$|host_key_checking = False|' /etc/ansible/ansible.cfg
