---
- hosts: docker-hosts
  remote_user: root
  roles:
  ###  - common
  tasks:
    - name: "Containes started"
      shell:
        docker run -h "{{ ansible_hostname }}container{{ item }}.example.com" -d r7perfsat
      with_sequence:
        count=500
    - name: "List container IDs"
      command:
        docker ps -q
      register: docker_ids
    - debug: var=docker_ids
    - name: "Cleanup containers IP list"
      file:
        path=/root/container-ips
        state=absent
      ###delegate_to: 127.0.0.1
      ###run_once: true
    - name: "Get IPs of containers"
      shell:
        docker inspect "{{ item }}" | python -c "import json,sys;obj=json.load(sys.stdin);print obj[0]['Id'], obj[0]['NetworkSettings']['IPAddress']" >>/root/container-ips
      with_items: "{{ docker_ids.stdout_lines }}"
      register: docker_ips
    # TODO: rewrite this into inventory - would shuffling work?
    - name: "Shuffle container IPs"
      shell:
        sort -R /root/container-ips >/root/container-ips.shuffled
      ###delegate_to: 127.0.0.1
      ###run_once: true
