---

- hosts: satellite6
  remote_user: root
  vars_files:
    - groups_vars/creds.yaml
    - groups_vars/generic.yaml
  roles:
    - common
    - rhsm
    - setup
    - pbench_client
    - satellite-populate
  tags:
    - setup_satellite
