---
- hosts: satellite6
  remote_user: root
  vars_files:
    - groups_vars/creds.yaml
    - groups_vars/generic.yaml
  roles:
    - { role: backup, when: backup is defined }
    - { role: upload-manifest, when: upload_manifest is defined }
    - { role: restore, when: restore is defined }
    - { role: add-product, when: add_product is defined }
    - { role: create-lifecycle, when: create_lifecycle is defined }
    - { role: enable-content, when: enable_content is defined }
    - { role: content-view-create, when: content_view_create is defined  }
    - { role: content-view-publish, when: content_view_publish is defined }
    # - { role: content-view-promote, when: content_view_promote is defined }
    - { role: sync-content, when: sync_content is defined }
    - { role: sync-capsule, when: sync_capsule is defined }
    - { role: register, when: register_content_host is defined }
    - { role: status_check, when: katello_check is defined }
