---
  # Taken from https://gist.github.com/rothgar/8793800
  #- name: "Build hosts file"
  #  lineinfile:
  #    dest=/etc/hosts
  #    regexp='.*{{ item }}$'
  #    line="{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
  #    state=present
  #  when: hostvars[item].ansible_default_ipv4.address is defined
  #  with_items: groups['all']

  - name: "We need localhost (IPv4) in hosts file"
    lineinfile:
      dest=/etc/hosts
      regexp='^127\.0\.0\.1\s+localhost localhost\.localdomain localhost4 localhost4\.localdomain4$'
      line="127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4"
      state=present
  - name: "We might need localhost (IPv6) in hosts file"
    lineinfile:
      dest=/etc/hosts
      regexp='^::1\s+localhost localhost\.localdomain localhost6 localhost6\.localdomain6$'
      line="::1   localhost localhost.localdomain localhost6 localhost6.localdomain6"
      state=present
  - name: "Build hosts file"
    lineinfile:
      dest=/etc/hosts
      regexp='.*{{ item }}$'
      line="{{ hostvars[item].ip }} {{ item }}"
      state=present
    when: hostvars[item].ip is defined
    with_items: "{{groups['all']}}"

  # Taken from http://stackoverflow.com/questions/21892603/how-to-make-ansible-execute-a-shell-script-if-a-package-is-not-installed
  - name: "Check if firewalld is installed"
    command:
      rpm -q firewalld
    register: firewalld_is_installed
    failed_when: firewalld_is_installed.rc > 1
    changed_when: no
  - name: "Disable firewalld"
    service:
      name=firewalld
      state=stopped
      enabled=no
    when: firewalld_is_installed.rc == 0

  - name: "SELinux is in Enforcing with Tragetted policy"
    selinux:
      policy=targeted
      state=enforcing
  - name: "File /etc/hosts have correct SELinux context (had issues before)"
    command:
      restorecon -vR /etc/hosts

  - name: "We can ping Google.com"
    wait_for:
      host=google.com
      port=443
      timeout=10
  - name: "We can ping Sat via 10GB network"
    wait_for:
      host=10.1.1.2
      port=22
      timeout=10
    ignore_errors: yes   # Sometimes satellite is down

  - name: "Command yum repolist returns"
    command:
      yum repolist

  #- name: "ntpd is stopped"
  #  service:
  #    name=ntpd
  #    state=stopped

  - name: "Time is synchronized"
    command:
      ntpdate tak.cesnet.cz

  #- name: "ntpd is started"
  #  service:
  #    name=ntpd
  #    state=started
...
