---
  - shell: |
      hammer --username '{{ sat_user }}' --password '{{ sat_pass }}' \
        product create --organization-id {{ orgid }} --name {{item}}
    with_indexed_items: "{{ products }}"
...
